spring:
  application:
    name: order-service
  mongodb:
    uri: ${MONGODB_URI_ORDER}
  data:
    mongodb:
      auto-index-creation: true

server:
  port: ${ORDER_SERVICE_PORT}
  error:
    include-message: always

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}
  instance:
    prefer-ip-address: true

logging:
  level:
    mss.orderservice: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs

momo:
  endpoint: https://test-payment.momo.vn/v2/gateway/api/create
  partnerCode: ${MOMO_PARTNER_CODE}
  accessKey: ${MOMO_ACCESS_KEY}
  secretKey: ${MOMO_SECRET_KEY}
  returnUrl: http://localhost:5173/payment/momo-return
  notifyUrl: ${MOMO_NOTIFY_URL}
