spring:
  application:
    name: product-service
  mongodb:
    uri: ${MONGODB_URI_PRODUCT}
  data:
    mongodb:
      auto-index-creation: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      spring.json.add.type.headers: false

server:
  port: ${PRODUCT_SERVICE_PORT}

app:
  internal-service-token: ${INTERNAL_SERVICE_TOKEN:${JWT_SECRET}}
  jwt:
    secret: ${JWT_SECRET}
    issuer: aiskin-user-service


  client:
    service-url:
      defaultZone: ${EUREKA_URI}
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:127.0.0.1}
    prefer-ip-address: false

logging:
  level:
    mss.productservice: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs

management:
  health:
    mongodb:
      enabled: false
